Recipe for extracting number of final participants
oughtinc/ice pull request #3
Opened 2022-09-19 09:28 UTC by CG80499

- Added FinalN recipe
- Added monoT5 agent for paragraph classification

2022-09-21 15:55 UTC, alexmojaki reviewed
Hello :wave: Please don't take this 'review' too seriously. I'm not an Ought employee, I'm just passing by.

2022-09-21 15:55 UTC, alexmojaki commented on ice/recipes/finalN.py
> +    return number_strings
```suggestion
    numbers_set = set("0123456789")
    return [
        word.replace("(", "")
            .replace(")", "")
            .replace("...", "")
            .replace("..", "")
            .rstrip(",.")
        for word in words
        if numbers_set.intersection(word)
    ]
```

1. This assumes that removing more than one trailing `,` or `.` is OK, which your original code does not.
2. Regexes or an actual library might be better suited here.
3. Is it fine to return strings containing numbers that clearly aren't numbers, like `"agley-2021.pdf"`?

2022-09-21 15:55 UTC, alexmojaki commented on ice/recipes/finalN.py
> +    answers = [(await answer_with_reasoning(prompt, cache_id=i)) for i in range(5)]
Should these happen in parallel?

2022-09-21 15:55 UTC, alexmojaki commented on ice/recipes/finalN.py
> +    log.warn(f"Total token usage: {total_token_usage}")
`warn` sounds a bit heavy for something expected?

2022-09-21 15:55 UTC, alexmojaki commented on ice/recipes/finalN.py
> +    return answers[0]
```suggestion
    answer_counts_by_number = collections.Counter(
        number
        for answer_numbers in numbers_in_answers
        for number in set(answer_numbers)  # only count each number once per answer
    )

    def score(answer_numbers):
        if answer_numbers:
            average_count = statistics.mean(
                answer_counts_by_number[number] for number in answer_numbers
            )
        else:
            average_count = 0
        return average_count, len(answer_numbers)

    answer, _ = max(
        zip(answers, numbers_in_answers),
        key=lambda t: score(t[1]),
    )
    return answer
```

2022-09-22 16:41 UTC, lslunis requested changes
I'd like to get ice/nn/weights out of this repo so that people can get started with a smaller download. That means:

1. We should do something like download them from S3 instead. I'm going to set that up soon, but might not get to it this week, and this PR shouldn't go in until that's done
2. I'm going to **rewrite git history** to make the repo smaller (and then obviously never do that again, because it's terrible). That might cause problems with eventually merging this PR, and I can help with that when the time comes

2022-09-22 16:59 UTC, alexmojaki commented
> I'd like to get ice/nn/weights out of this repo so that people can get started with a smaller download.

I'm not saying you shouldn't do this, but if you're concerned about this when the model weights are 238KB, then I think I should point out that I ran out of disk space because the Python dependencies take up 4.5 GB, of which 3.3 GB is `torch`.

2022-09-22 17:05 UTC, alexmojaki commented
Ah, I see you're probably talking more about the existing 6.4 MB than what's in this PR, that changes things.

2022-09-24 02:16 UTC, closed without merging

2022-09-24 02:54 UTC, lslunis commented
Looks like when I force-pushed main, it caused this PR to close(!). I'm going to reopen it tomorrow or Sunday based on the new main.